orbs:
  newman: postman/newman@0.0.2
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ../GroverTests.postman_collection.json
          environment: ../Grover_TestEnvironment.postman_environment.json